name: fastclean
description: "A fast way to clean your photos."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  cupertino_icons: ^1.0.6
  photo_manager: ^3.0.0
  photo_manager_image_provider: ^2.0.0
  image: ^4.1.0
  crypto: ^3.0.3
  google_fonts: ^6.3.2
  disk_space_plus: ^0.2.6
  google_mlkit_face_detection: ^0.11.0
  device_info_plus: ^10.1.0
  shimmer: ^3.0.0
  photo_view: ^0.15.0
  shared_preferences: ^2.2.3
  flutter_staggered_animations: ^1.1.1
  percent_indicator: ^4.2.5
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/

flutter_native_splash:
  color: "#222122"
  image: android/app/src/main/res/mipmap-mdpi/launcher_icon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/logo mk 4.png"
